YONK-762: Discussions score issue fixed
edx-solutions/discussion-edx-platform-extensions pull request #13
Opened 2017-09-28 12:13 UTC by aamishbaloch

Discussions scores are now updating for the learners who respond to a post, if user deletes his own actual post or comment.

2017-09-28 12:13 UTC, aamishbaloch commented
@ziafazal Can you review this?

2017-09-28 12:16 UTC, aamishbaloch commented
@ziafazal Changes in platforms can be seen in [ee6c70da1624abe91b28612386b56082387253d3](https://github.com/edx-solutions/edx-platform/commit/ee6c70da1624abe91b28612386b56082387253d3) commit.

2017-09-28 13:39 UTC, ziafazal requested changes
@aamishbaloch I'm do with first pass of code review.

2017-09-28 13:39 UTC, ziafazal commented on social_engagement/engagement.py
> +    from lms.djangoapps.discussion_api.views import CommentViewSet
Put this after docstring.

2017-09-28 13:39 UTC, ziafazal commented on social_engagement/engagement.py
> +        response = CommentViewSet().list(request)
this is duplicate code block it can be removed.

2017-09-28 13:39 UTC, ziafazal commented on social_engagement/engagement.py
> +            response = CommentViewSet().retrieve(request, response_comment_id)
duplicate code block.

2017-09-28 13:39 UTC, ziafazal commented on social_engagement/engagement.py
> +    response = ThreadViewSet().retrieve(request, thread_id)
I think this code block should be in separate method.

2017-09-28 13:39 UTC, ziafazal commented on social_engagement/engagement.py
> +    if parent_id:
why this needs to be here?

2017-09-28 13:39 UTC, ziafazal commented on social_engagement/handlers.py
> +        users = User.objects.filter(~Q(id=user_id), username__in=involved_users)
nit: may using this filter is more readable.
```
 users = User.objects.filter(username__in=involved_users).exclude(id=user_id)
```

2017-09-29 13:10 UTC, aamishbaloch commented
@ziafazal Done with the changes. Can you review the changes?

2017-09-29 13:37 UTC, ziafazal approved these changes
👍

2017-09-29 13:45 UTC, merged